language: java
install: mvn install -DskipTests=true
notifications:
  email:
    - okrammarko@gmail.com
    - spmva@genoprime.com
    - josh@fortytwo.net
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
